version: "3"

services:
  db:
    image: postgres
    container_name: db
  dj:
    container_name: dj
    build: django
    command: python manage.py runserver 0.0.0.0:80
    volumes:
      - ./django:/code
    ports:
      - "80:80"
    depends_on:
      - db
  ng:
    container_name: ng
    build: angular
    ports:
      - "4200:80"
